FROM python:3.11.2

RUN mkdir /mango_read

WORKDIR /mango_read

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . /mango_app

CMD ["python","manage.py runserver"]